const users = [
  {
    ID: "1",
    lastName: "上野",
    firstName: "樒",
    lastNameKana: "うえの",
    firstNameKana: "しきみ",
  },
  {
    ID: "2",
    lastName: "古佐小",
    firstName: "宮賀",
    lastNameKana: "こさこ",
    firstNameKana: "きゅうが",
  },
  {
    ID: "3",
    lastName: "倉成",
    firstName: "勝子",
    lastNameKana: "くらなり",
    firstNameKana: "しょうこ",
  },
  {
    ID: "4",
    lastName: "外塚",
    firstName: "玄心",
    lastNameKana: "とづか",
    firstNameKana: "げんしん",
  },
  {
    ID: "5",
    lastName: "今村",
    firstName: "えつみ",
    lastNameKana: "いまむら",
    firstNameKana: "えつみ",
  },
  {
    ID: "6",
    lastName: "魚井",
    firstName: "美里",
    lastNameKana: "うおい",
    firstNameKana: "みさと",
  },
  {
    ID: "7",
    lastName: "久田",
    firstName: "進理",
    lastNameKana: "くだ",
    firstNameKana: "しんり",
  },
  {
    ID: "8",
    lastName: "今野",
    firstName: "稀裕",
    lastNameKana: "こんの",
    firstNameKana: "まひろ",
  },
  {
    ID: "9",
    lastName: "渡部",
    firstName: "正岳",
    lastNameKana: "わたなべ",
    firstNameKana: "せいがく",
  },
  {
    ID: "10",
    lastName: "島方",
    firstName: "遊満",
    lastNameKana: "しまかた",
    firstNameKana: "ゆま",
  },
  {
    ID: "11",
    lastName: "響",
    firstName: "三莉",
    lastNameKana: "ひびき",
    firstNameKana: "みり",
  },
  {
    ID: "12",
    lastName: "長尾",
    firstName: "嘉子",
    lastNameKana: "ながお",
    firstNameKana: "かこ",
  },
  {
    ID: "13",
    lastName: "濁川",
    firstName: "治",
    lastNameKana: "にごりがわ",
    firstNameKana: "おさむ",
  },
  {
    ID: "14",
    lastName: "片伊勢",
    firstName: "近夏璃",
    lastNameKana: "かたいせ",
    firstNameKana: "ちかなり",
  },
  {
    ID: "15",
    lastName: "牟",
    firstName: "裕貴",
    lastNameKana: "も",
    firstNameKana: "ゆうき",
  },
  {
    ID: "16",
    lastName: "貝澤",
    firstName: "匡裕",
    lastNameKana: "かいざわ",
    firstNameKana: "まさひろ",
  },
  {
    ID: "17",
    lastName: "杉山",
    firstName: "結利",
    lastNameKana: "すぎやま",
    firstNameKana: "ゆいり",
  },
  {
    ID: "18",
    lastName: "林保",
    firstName: "磨玖",
    lastNameKana: "りんぽ",
    firstNameKana: "みがく",
  },
  {
    ID: "19",
    lastName: "百千万億",
    firstName: "紀子",
    lastNameKana: "つもる",
    firstNameKana: "きこ",
  },
  {
    ID: "20",
    lastName: "湶",
    firstName: "さだ",
    lastNameKana: "あばら",
    firstNameKana: "さだ",
  },
];

export default users;
